/*! Open Historia — portions (mobile HUD wiring + advisor/forces launchers) © 2026 Nicholas Krol, MIT (see src/Editor/LICENSE). */
import React, { Suspense, lazy, useCallback, useEffect, useMemo, useState } from "react";
import dayjs from "dayjs";
import "dayjs/locale/fr";
import { SettingsButton, SettingsMenu } from "./settings";
import { LibraryTopBar, TOP_BAR_OFFSET } from "./libraryBar";
import { useLibraryState } from "../../runtime/library.js";
import { DateWidget } from "./time";
import { Other } from "./other";
import { Toolbar } from "./chat";
import { Correspondence } from "./correspondence.jsx";
import { College } from "./college.jsx";
import { HAS_MAP, HOME_SECTION } from "../../runtime/edition.js";
import { Search } from "./search";
import { ForcesPanel } from "./forces";
import { Bulletin } from "./bulletin.jsx";
import { Ordres, Registre } from "./cahiers.jsx";
import { nextEdition } from "../../runtime/nextEdition.js";
import { readActionsState, readGameData, readWorldState } from "../../runtime/gameState.js";
import {
  getStoredProvider,
  loadProviderSettingsFormState,
  normalizeProvider,
  persistProviderSetting,
} from "../AI/providerConfig.js";

// The advisor drawer is user-resizable — drag its left edge (see advisor.jsx).
// Width is kept in px so the drag maps 1:1 to the pointer, persisted in
// localStorage, and clamped to a readable min and the current viewport.
const ADVISOR_MIN_WIDTH = 280;
const ADVISOR_DEFAULT_WIDTH = 320; // 20rem, the old fixed width
const clampAdvisorWidth = (px) => {
  const max = (typeof window !== "undefined" ? window.innerWidth : 1280) - 16;
  return Math.round(Math.min(Math.max(px, Math.min(ADVISOR_MIN_WIDTH, max)), max));
};
const readAdvisorWidth = () => {
  try {
    const saved = Number(localStorage.getItem("oh-advisor-width"));
    if (Number.isFinite(saved) && saved > 0) return clampAdvisorWidth(saved);
  } catch { /* private-mode storage — fall through to default */ }
  return clampAdvisorWidth(ADVISOR_DEFAULT_WIDTH);
};
const baseStyle = {
  position: "fixed",
  backgroundColor: "var(--oh-plate)",
 
  zIndex: 9999,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "var(--oh-text)",
  fontFamily: "inherit",
  borderRadius: "12px",
  border: "1px solid var(--oh-line)",
  boxShadow: "0 4px 6px -1px rgba(0,0,0,0.2)",
};
const LazyAdvisorPanel = lazy(() =>
  import("./advisor").then((module) => ({ default: module.AdvisorPanel })),
);
const LazyCheatsPanel = lazy(() =>
  import("./cheats").then((module) => ({ default: module.CheatsPanel })),
);

const checkWebGL = () => {
  try {
    const canvas = document.createElement("canvas");
    return !!(
      window.WebGLRenderingContext &&
      (canvas.getContext("webgl") || canvas.getContext("experimental-webgl"))
    );
  } catch {
    return false;
  }
};

// The paper's sections, always reachable at the foot of the page. The record of
// the turn is what the game opens on; the adviser and the ledger are sections of
// the same sheet rather than drawers sliding over a map; the map is a section
// too. None of them floats over another, so the bar stays put in all of them.
// Written in French, like every string the player reads. The old rule put
// English in the source and left the translation to the runtime translator,
// whose offline safety net (public/lang) is generated by hand and had gone six
// days stale — so the game published to Vercel opened half in English. French
// here needs no model, no key and no regenerated pack.
// Les six cahiers de la maquette journal, dans son ordre. Les ordres et le
// registre étaient des blocs de la colonne droite de l'édition ; ils en sortent
// (cahiers.jsx) parce que la maquette leur donne une page.
//
// Le conseiller n'est plus un cahier : la maquette en fait un bouton du bloc
// d'ordre — on le consulte sur un geste précis, on ne va pas « dans » lui. Il
// reste atteignable depuis les ordres et depuis son onglet dans les caisses.
const SECTIONS = [
  ["bulletin", "Édition du tour"],
  ["orders", "Ordres"],
  ["register", "Registre"],
  // The room that decides, drawn seat by seat, and the place to argue with it.
  ["college", "Collège"],
  ["stats", "Caisses"],
  ["messages", "Correspondance"],
  // The atlas, in the edition that has one (runtime/edition.js). The Holy See
  // game is played in the paper, and its polity owns half a square kilometre.
  ...(HAS_MAP ? [["map", "Carte"]] : []),
];

// La barre commune de la maquette : les cahiers dans l'ordre, et à droite un
// seul bouton. Elle remplace la barre de sections qui vivait en pied de page
// et le cahier « Prochaine édition », devenu ce bouton — la date d'arrivée est
// dite AVANT qu'on clique, parce qu'un joueur ne devrait pas avoir à ouvrir une
// page pour savoir ce qu'un bouton va lui coûter en jours.
//
// Pas de réglage de durée ici : le moteur fixe la date d'après ce qui est au
// dossier (runtime/nextEdition.js), et c'est lui qui a raison.
const ViewTabs = ({ current, onSelect }) => {
  const [game, setGame] = useState(null);
  const [world, setWorld] = useState(null);
  const [actions, setActions] = useState([]);

  // Il n'y a pas de bus d'état dans ce jeu : chaque page relit ce dont elle a
  // besoin. La barre relit au changement de cahier, ce qui couvre le retour sur
  // l'édition après un passage sous presse.
  useEffect(() => {
    let vivant = true;
    Promise.all([
      readGameData().catch(() => null),
      readWorldState({ force: true }).catch(() => null),
      readActionsState({ force: true }).catch(() => []),
    ]).then(([g, w, a]) => {
      if (!vivant) return;
      setGame(g);
      setWorld(w);
      setActions(Array.isArray(a) ? a : []);
    });
    return () => { vivant = false; };
  }, [current]);

  const aujourdhui = game?.gameDate ? dayjs(game.gameDate).locale("fr") : null;
  const arrivee = useMemo(
    () => nextEdition(world, actions, { today: game?.gameDate || "" }),
    [world, actions, game?.gameDate],
  );
  const jours = Number(arrivee?.days) || 0;
  const dateArrivee = aujourdhui && aujourdhui.isValid() && jours > 0
    ? aujourdhui.add(jours, "day")
    : null;

  const cahier = (id, label) => {
    const actif = current === id;
    return (
      <button
        type="button"
        key={id}
        onClick={() => onSelect(id)}
        style={{
          background: actif ? "var(--oh-line-strong)" : "transparent",
          border: 0,
          color: actif ? "var(--oh-on-accent)" : "var(--oh-text)",
          cursor: "pointer",
          fontFamily: "var(--oh-font-label)",
          fontSize: "var(--oh-t-xs)",
          fontWeight: "var(--oh-label-weight)",
          letterSpacing: "var(--oh-label-track)",
          padding: "0.5rem 0.9rem",
          textTransform: "var(--oh-label-case)",
          whiteSpace: "nowrap",
        }}
      >
        {label}
      </button>
    );
  };

  return (
    <div
      style={{
        alignItems: "center",
        background: "var(--oh-plate)",
        borderBottom: "2px solid var(--oh-line)",
        display: "flex",
        gap: "0.4rem",
        left: 0,
        padding: "0.35rem 0.9rem",
        position: "fixed",
        right: 0,
        top: `calc(${TOP_BAR_OFFSET} + 3.5rem)`,
        zIndex: 10001,
      }}
    >
      {/* Le bandeau du journal : son nom, et le jour qu'on est en train de jouer. */}
      <span
        className="oh-barre-titre"
        style={{
          color: "var(--oh-text-strong)",
          fontFamily: "var(--oh-font-display)",
          fontSize: "var(--oh-t-md)",
          fontWeight: 800,
          letterSpacing: "-0.02em",
          whiteSpace: "nowrap",
        }}
      >
        Saint-Siège
      </span>
      {aujourdhui && aujourdhui.isValid() && (
        <span className="oh-barre-titre" style={{ borderLeft: "1px solid var(--oh-line)", color: "var(--oh-text-dim)", fontSize: "var(--oh-t-xs)", marginLeft: "0.2rem", paddingLeft: "0.7rem", whiteSpace: "nowrap" }}>
          {aujourdhui.format("D MMMM YYYY")}
        </span>
      )}

      <div className="oh-barre-cahiers" style={{ display: "flex", flex: 1, gap: "0.2rem", justifyContent: "center", overflowX: "auto" }}>
        {SECTIONS.map(([id, label]) => cahier(id, label))}
      </div>

      {/* Un seul bouton, et ce qu'il coûte écrit à côté. */}
      <button
        type="button"
        onClick={() => onSelect("next")}
        style={{
          background: "var(--oh-accent)",
          border: 0,
          color: "var(--oh-on-accent)",
          cursor: "pointer",
          fontFamily: "var(--oh-font-label)",
          fontSize: "var(--oh-t-xs)",
          fontWeight: "var(--oh-label-weight)",
          letterSpacing: "var(--oh-label-track)",
          padding: "0.5rem 1rem",
          textTransform: "var(--oh-label-case)",
          whiteSpace: "nowrap",
        }}
      >
        Tour suivant
      </button>
      {dateArrivee && (
        <span
          className="oh-barre-arrivee"
          style={{
            background: "var(--oh-line-strong)",
            color: "var(--oh-on-accent)",
            fontSize: "var(--oh-t-xs)",
            padding: "0.5rem 0.8rem",
            whiteSpace: "nowrap",
          }}
        >
          → {dateArrivee.format("D MMMM YYYY")} · {jours} j
        </span>
      )}
    </div>
  );
};

const WebGLWarningPopup = () => (
  <div
    style={{
      position: "fixed",
      inset: 0,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 9999,
    }}
  >
    <div
      style={{
        backgroundColor: "var(--oh-plate)",
        border: "1px solid var(--oh-alert)",
        borderRadius: "12px",
        padding: "2rem",
        maxWidth: "420px",
        width: "90%",
        color: "var(--oh-text)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
        textAlign: "center",
      }}
    >
      <div
        style={{
          fontSize: "var(--oh-t-xl)",
          marginBottom: "0.75rem",
          color: "var(--oh-alert)",
          display: "flex",
          justifyContent: "center",
        }}
      >
        ⚠️
      </div>
      <h2 style={{ margin: "0 0 0.75rem", fontSize: "var(--oh-t-lg)", color: "var(--oh-alert)" }}>
        WebGL Not Available
      </h2>
      <p style={{ margin: "0 0 0.5rem", lineHeight: 1.6, color: "var(--oh-text)", fontSize: "var(--oh-t-sm)" }}>
        This application requires <strong style={{ color: "var(--oh-text)" }}>WebGL</strong> to render
        the map, but it doesn't appear to be supported or enabled in your browser.
      </p>
      <p style={{ margin: "0 0 1.5rem", lineHeight: 1.6, color: "var(--oh-text-dim)", fontSize: "var(--oh-t-xs)" }}>
        Try enabling hardware acceleration in your browser settings, updating your graphics
        drivers, or switching to a WebGL-supported browser such as Chrome or Firefox.
      </p>
    </div>
  </div>
);

const AdvisorButton = ({ isAdvisorOpen, rightShift, onToggle }) => (
  <button onClick={onToggle} style={{
    ...baseStyle,
    bottom: "3.1rem", right: rightShift,
    height: "4rem", width: "4rem",
    cursor: "pointer", fontSize: "var(--oh-t-lg)",
    transition: "right 0.35s cubic-bezier(0.4, 0, 0.2, 1)",
  }}>🧭</button>
);

const Main = ({
  mapRef,
  isGlobeEnabled,
  isTerrainEnabled,
  setIsGlobeEnabled,
  setIsTerrainEnabled,
}) => {
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isCheatsOpen, setIsCheatsOpen] = useState(false);
  const [shouldLoadCheats, setShouldLoadCheats] = useState(false);
  const [isAdvisorOpen, setIsAdvisorOpen] = useState(false);
  const [advisorWidth, setAdvisorWidth] = useState(readAdvisorWidth);
  const [isForcesOpen, setIsForcesOpen] = useState(false);
  const [advisorSection, setAdvisorSection] = useState("advisor");
  // The game opens on the bulletin, not on the globe. What a player acts on is
  // what the world did to them since last time; the map is where they go to look
  // something up, and it is one tab away at the foot of the page. The bulletin is
  // its own page (bulletin.jsx), not a panel of the map view.
  const [section, setSection] = useState("bulletin");
  // Bumped by the "Next edition" tab so the bulletin scrolls to its press block.
  const [pressFocus, setPressFocus] = useState(0);
  const [activeBottomPanel, setActiveBottomPanel] = useState(null);
  const [shouldLoadAdvisor, setShouldLoadAdvisor] = useState(false);
  const [isFullscreenEnabled, setIsFullscreenEnabled] = useState(false);
  const [showWebGLWarning, setShowWebGLWarning] = useState(false);

  const [apiProvider, setApiProvider] = useState(() => getStoredProvider());
  const [providerSettings, setProviderSettings] = useState(() => loadProviderSettingsFormState());
  const { games, loaded } = useLibraryState();
  // No games -> nothing to simulate (the main menu covers the empty world).
  const hasNoGames = loaded && (games?.length ?? 0) === 0;

  useEffect(() => {
    if (!checkWebGL()) setShowWebGLWarning(true);
  }, []);

  // Idle diplomacy drip: each real-world minute the game is open (and has a
  // running game), there is a small chance a polity messages the player's
  // inbox unprompted. Everything that could break it is guarded inside
  // maybeSendIdleDiplomacy — it skips entirely while a time skip, game-master
  // command, or catalyst stage is in flight, never overlaps itself, and stays
  // silent on any failure. Hidden tabs don't roll the dice.
  useEffect(() => {
    if (hasNoGames) return undefined;
    const iv = setInterval(() => {
      if (document.visibilityState !== "visible") return;
      import("../AI/gameplay.js")
        .then(({ maybeSendIdleDiplomacy }) => maybeSendIdleDiplomacy())
        .catch(() => {});
    }, 60000);
    return () => clearInterval(iv);
  }, [hasNoGames]);

  useEffect(() => {
    if (isAdvisorOpen) setShouldLoadAdvisor(true);
  }, [isAdvisorOpen]);

  useEffect(() => {
    localStorage.setItem("Fullscreen", JSON.stringify(isFullscreenEnabled));
  }, [isFullscreenEnabled]);

  useEffect(() => {
    localStorage.setItem("api_provider", normalizeProvider(apiProvider));
  }, [apiProvider]);

  useEffect(() => {
    if (isSettingsOpen) {
      setApiProvider(getStoredProvider());
      setProviderSettings(loadProviderSettingsFormState());
    }
  }, [isSettingsOpen]);

  const handleProviderSettingChange = (key, value) => {
    setProviderSettings((prev) => ({ ...prev, [key]: value }));
    persistProviderSetting(key, value);
  };

  const toggleFullscreen = (shouldBeFull) => {
    // Mobile Safari (iOS/iPad) exposes the Fullscreen API webkit-prefixed, and
    // iPhone Safari doesn't support element fullscreen at all — so probe for the
    // right methods and never call an undefined one (which threw before, so the
    // button silently failed on mobile).
    const el = document.documentElement;
    const fsElement = document.fullscreenElement || document.webkitFullscreenElement;
    const request = el.requestFullscreen || el.webkitRequestFullscreen;
    const exit = document.exitFullscreen || document.webkitExitFullscreen;
    try {
      if (shouldBeFull) {
        if (!fsElement && request) {
          const result = request.call(el);
          if (result && typeof result.catch === "function") {
            result.catch((error) => console.error("Error with fullscreen", error));
          }
        }
      } else if (fsElement && exit) {
        exit.call(document);
      }
    } catch (error) {
      console.error("Error with fullscreen", error);
    }
  };

  useEffect(() => {
    const handleFullscreenChange = () =>
      setIsFullscreenEnabled(!!(document.fullscreenElement || document.webkitFullscreenElement));
    document.addEventListener("fullscreenchange", handleFullscreenChange);
    document.addEventListener("webkitfullscreenchange", handleFullscreenChange);
    return () => {
      document.removeEventListener("fullscreenchange", handleFullscreenChange);
      document.removeEventListener("webkitfullscreenchange", handleFullscreenChange);
    };
  }, []);

  const openAdvisor = useCallback(() => {
    setIsAdvisorOpen(true);
  }, []);

  // Called on every pointermove while the user drags the advisor's edge.
  const handleAdvisorResize = useCallback((px) => {
    setAdvisorWidth(() => {
      const w = clampAdvisorWidth(px);
      try { localStorage.setItem("oh-advisor-width", String(w)); } catch { /* ignore */ }
      return w;
    });
  }, []);

  // Keep the saved width valid if the window shrinks below it.
  useEffect(() => {
    const onResize = () => setAdvisorWidth((w) => clampAdvisorWidth(w));
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  const onBulletin = section === "bulletin";
  const onMessages = section === "messages";
  const onOrdres = section === "orders";
  const onRegistre = section === "register";
  // Which page of the paper is showing. The adviser and the ledger are the same
  // panel under two tabs; the map is the section with nothing open on top of it.
  const onCollege = section === "college";
  const currentSection = onBulletin
    ? "bulletin"
    : onMessages
    ? "messages"
    : onOrdres
    ? "orders"
    : onRegistre
    ? "register"
    : onCollege
    ? "college"
    : isAdvisorOpen
      ? advisorSection
      : HOME_SECTION;
  // A section of the paper takes the page; the old right-hand drawer is what the
  // adviser is when the map is showing under it.
  const advisorIsSection = isAdvisorOpen && !onBulletin && !onCollege && !onOrdres && !onRegistre;
  const rightShift = isAdvisorOpen ?`calc(${advisorWidth}px + 0.5rem)` : "0.5rem";
  const toggleBottomPanel = useCallback((panelName) => {
    setActiveBottomPanel((currentPanel) => (
      currentPanel === panelName ? null : panelName
    ));
  }, []);

  // One section at a time: opening one closes the others, which is what makes
  // them read as pages of a paper rather than as stacked drawers.
  const selectSection = useCallback((next) => {
    // "Next turn" is an action, not a page: it opens the time panel over the
    // map and leaves the section on the map until the jump is done.
    if (next === "next") {
      // The next turn is the next edition, printed from the bulletin's own
      // press block (bulletin.jsx Press): the tab opens the sheet and lands the
      // reader on it. The block itself holds the presses until the pope has a
      // name and a programme (runtime/inauguration.js).
      setSection("bulletin");
      setIsAdvisorOpen(false);
      setActiveBottomPanel(null);
      setPressFocus((n) => n + 1);
      return;
    }
    setSection(next);
    setActiveBottomPanel(null);
    const advisorWanted = next === "advisor" || next === "stats";
    setIsAdvisorOpen(advisorWanted);
    if (advisorWanted) {
      setShouldLoadAdvisor(true);
      setAdvisorSection(next);
    }
  }, []);

  return (
    <>
      {showWebGLWarning && <WebGLWarningPopup />}
      {onMessages && (
        <Correspondence />
      )}
      {onBulletin && (
        <Bulletin onOpenAdvisor={openAdvisor} pressFocus={pressFocus} />
      )}
      {onOrdres && <Ordres onOpenAdvisor={openAdvisor} />}
      {onRegistre && <Registre />}
      {section === "college" && <College />}
      <ViewTabs current={currentSection} onSelect={selectSection} />
      <LibraryTopBar />
      <DateWidget
        activePanel={activeBottomPanel}
        mapRef={mapRef}
        onSetPanel={setActiveBottomPanel}
        onTogglePanel={toggleBottomPanel}
        rightShift={rightShift}
        topOffset={TOP_BAR_OFFSET}
      />
      {/* While the bulletin holds the page, the round floating buttons would
          print on top of it. They belong to the map view. */}
      {!onBulletin && !onMessages && !onOrdres && !onRegistre && (
        <>
          <Toolbar
            onOpenAdvisor={openAdvisor}
            activePanel={activeBottomPanel}
            onTogglePanel={toggleBottomPanel}
          />
          <Other rightShift={rightShift} />
          <Search mapRef={mapRef} />
        </>
      )}
      <ForcesPanel
        mapRef={mapRef}
        topOffset={TOP_BAR_OFFSET}
        open={isForcesOpen}
        onToggle={() => setIsForcesOpen((v) => !v)}
      />
      {!onBulletin && !onMessages && (
        <AdvisorButton
          isAdvisorOpen={isAdvisorOpen}
          rightShift={rightShift}
          onToggle={() => setIsAdvisorOpen(!isAdvisorOpen)}
        />
      )}
      <Suspense fallback={null}>
        {shouldLoadAdvisor && (
          <LazyAdvisorPanel
            isAdvisorOpen={isAdvisorOpen}
            onClose={() => setIsAdvisorOpen(false)}
            width={advisorWidth}
            onResize={handleAdvisorResize}
            fullPage={advisorIsSection}
            section={advisorIsSection ? advisorSection : null}
            onSection={advisorIsSection ? setAdvisorSection : null}
          />
        )}
      </Suspense>
      <Suspense fallback={null}>
        {shouldLoadCheats && (
          <LazyCheatsPanel open={isCheatsOpen} onClose={() => setIsCheatsOpen(false)} onOpenForces={() => { setIsCheatsOpen(false); setIsForcesOpen(true); }} />
        )}
      </Suspense>
      <SettingsButton
        topOffset={TOP_BAR_OFFSET}
        onToggle={() => setIsSettingsOpen(!isSettingsOpen)}
      />
      {isSettingsOpen && (
        <SettingsMenu
          discordUrl="https://discord.gg/QaqAK7fQAg"
          redditUrl="https://www.reddit.com/r/OpenHistoria"
          githubUrl="https://github.com/Open-Historia/open-historia"
          onOpenCheats={() => {
            setShouldLoadCheats(true);
            setIsCheatsOpen(true);
            setIsSettingsOpen(false);
          }}
          topOffset={TOP_BAR_OFFSET}
          isFullscreenEnabled={isFullscreenEnabled}
          isGlobeEnabled={isGlobeEnabled}
          isTerrainEnabled={isTerrainEnabled}
          onToggleFullscreen={() => {
            const newState = !isFullscreenEnabled;
            setIsFullscreenEnabled(newState);
            toggleFullscreen(newState);
          }}
          onToggleGlobe={() => setIsGlobeEnabled(!isGlobeEnabled)}
          onToggleTerrain={() => setIsTerrainEnabled(!isTerrainEnabled)}
          apiProvider={apiProvider}
          onApiProviderChange={setApiProvider}
          providerSettings={providerSettings}
          onProviderSettingChange={handleProviderSettingChange}
        />
      )}
    </>
  );
};

export default Main;
