// Interface strings into French, one explicit pair at a time.
//
// The player's instruction: "je veux que tu code tout en français, j'ai toujours
// été clair là-dessus." He had been; the rule in the source said the opposite,
// because the old design put English in the source and left translation to the
// runtime translator — whose offline packs (public/lang) are generated by hand
// and had gone six days stale by the time the game was published to Vercel.
//
// Written as a script rather than done by hand because the count is what makes
// it error-prone, and as an explicit TABLE rather than a regex because a regex
// over source code eventually replaces a word inside an identifier, a comment or
// a URL. Every pair below is a full, unique line fragment; a pair that does not
// match is reported rather than skipped in silence.

import fs from "node:fs";
import path from "node:path";

const EDITS = [
  ["src/Game/GameUI/chat.jsx", '>Cancel</button>', '>Annuler</button>'],
  ["src/Game/GameUI/chat.jsx", '{page ? "Send" : "🚀"}', '{page ? "Envoyer" : "🚀"}'],
  ["src/Game/GameUI/cheats.jsx", '{isEditing ? "Close" : "Edit"}', '{isEditing ? "Fermer" : "Modifier"}'],
  ["src/Game/GameUI/FactionCreator.jsx", '>Cancel</button>', '>Annuler</button>'],
  ["src/Game/GameUI/libraryBar.jsx", '{isBusy ? "Saving..." : "Save"}', '{isBusy ? "Enregistrement…" : "Enregistrer"}'],
  ["src/Game/GameUI/libraryBar.jsx", '{playGameId ? "Done" : "Cancel"}', '{playGameId ? "Terminé" : "Annuler"}'],
  ["src/Game/GameUI/organizationsView.jsx", '>Cancel</button>', '>Annuler</button>'],
  ["src/Game/GameUI/scenarios.jsx", '{isBusy ? "Saving..." : "Save"}', '{isBusy ? "Enregistrement…" : "Enregistrer"}'],
  ["src/Game/GameUI/search.jsx", 'title={expanded ? "Close" : "Search place"}', 'title={expanded ? "Fermer" : "Chercher un lieu"}'],
];

// The cheats panel's own button, which the line-based report truncated.
const EXTRA = [
  ["src/Game/GameUI/cheats.jsx", 469, /(<button[^>]*onClick=\{[^}]*\}[^>]*>)\s*Cancel\s*(<\/button>)/, "$1Annuler$2"],
];

let changed = 0;
const missing = [];

for (const [file, from, to] of EDITS) {
  const full = path.resolve(file);
  const before = fs.readFileSync(full, "utf8");
  if (!before.includes(from)) { missing.push(`${file}: ${from}`); continue; }
  const after = before.split(from).join(to);
  fs.writeFileSync(full, after);
  const n = before.split(from).length - 1;
  changed += n;
  console.log(`${file} — ${n}× ${JSON.stringify(from)} → ${JSON.stringify(to)}`);
}

for (const [file, line, pattern, replacement] of EXTRA) {
  const full = path.resolve(file);
  const lines = fs.readFileSync(full, "utf8").split(/\r?\n/);
  const i = line - 1;
  if (!lines[i] || !pattern.test(lines[i])) { missing.push(`${file}:${line} (pattern)`); continue; }
  lines[i] = lines[i].replace(pattern, replacement);
  fs.writeFileSync(full, lines.join("\n"));
  changed += 1;
  console.log(`${file}:${line} — patched`);
}

console.log(`\n${changed} replacement(s).`);
if (missing.length) {
  console.log(`\nNOT FOUND (${missing.length}) — these need looking at by hand:`);
  for (const m of missing) console.log(`  ${m}`);
  process.exit(1);
}
